### ISSUE TITLE
Spike: Replace ActiveMq with Amazon SQS

### ISSUE THREAD

**Issue by julianghionoiu** [io-accelerate/tdl-client-java#4]
# Spike: Replace ActiveMq with Amazon SQS
## Context

The clients consume messages and publish responses using a queue system.
We are currently using ActiveMq which works fine but has some drawbacks:

1. **Scalability and availability**
Making the ActiveMq highly availably it is a pain, this means that the service can go down at any point.
In Prod, the ActiveMq instance crashed due to OutOfMemory following a malicious attack.

2. **Security**
It is theoretically possible for a user to interact with another active user's queue if both are active at the same time.
ActiveMq also listens on non-standard ports which means it might get blocked by the client's firewall

3. **Cost of maintenance and support** 
You have to deploy and manage the service.
Also, you need to keep an EC2 instance running, which adds to the cost.

4. **Availability of client libraries**
When adding support for a new programming language, the first thing we need to find is an ActiveMq client or a STOMP client. At the moment the clients for ActiveMq differ in terms of quality and features. This makes it harder to add support for new languages and maintain existing ones.

## Scope of Spike

The purpose of this spike is to investigate wether AWS SQS is a viable alternative to the way we use ActiveMq.

The requirements are captured by the acceptance tests and the spike is considered successful if all tests are passing.

Areas to investigate:
- How SQS manages message acknowledgements, if the client fails we should not lose the messages and another client should be able to pick that up immediately
- What control do we have on the batching and sequencing of messages
- How do you detect if there are no messages in the queue (timeouts?)

## Notes

This is a spike so the code will be deleted afterwards.

**Comment by neomatrix369** [comment]
1) Do we have sufficient acceptance tests to capture the current ActiveMQ behaviours?

	a) > In Prod, the ActiveMq instance crashed due to OutOfMemory following a malicious attack.

	Can we reproduce this? It is worth doing this, so we can cross check this when we have Amazon SQS up and running
	b) > Security
		Same query as above?

	c) > Availability of client libraries
	    Wrt to Amazon SQS is the client available for multiple languages

2) Which tests are worth looking at to understand an end-to-end cycle?

3) How tighty coupled is the code that replacing the ActiveMQ component will be seamless?

4) What are the important end-to-end flows between external components, ActiveMQ and tdl-client-java?

5) Are there any tests for the below concerns, can they be easily tested or simulated?

	- How SQS manages message acknowledgements, if the client fails we should not lose the messages and another client should be able to pick that up immediately
	- What control do we have on the batching and sequencing of messages
	- How do you detect if there are no messages in the queue (timeouts?)
6) How to or where to look for a setup that uses ActiveMQ so the tdl-client-java can be used to sent messages? Is dpnt-coverage or dpnt-video a good place? Basically I want an environment where I can send messages via the client to ActiveMQ (the way it runs in Prod) and see the message go through the end-to-end cycle.

7) Any end-to-end flow (diagrams) available that plots the whole lifecycle of different message lifecycles  (important ones)?

I hope my questions are clear, would be great to see the answered applied above into the description of the issue.

**Comment by julianghionoiu** [comment]
1. I would say yes, except the security requirement.
a. AWS SQS is a service managed by Amazon so they provide the availability as opposed to running our own ActiveMq instance
b. Security will be provided by IAM policy and that is covered by the project that generates client credentials: https://github.com/julianghionoiu/tdl-auth
c. We are going to leverage the fact that SQS is a rest interface and Amazon has created libraries for lots of languages

2.  The clients are covered by an extensive set of acceptance tests. They all run the same Gherkin files: - queue interaction: https://github.com/julianghionoiu/tdl-client-spec/blob/master/queue/QueueRunner.feature
- challenge server interaction: https://github.com/julianghionoiu/tdl-client-spec/blob/master/runner/ChallengeSession.feature

3. The first phase will not be replacing, but rather extending to add support for SQS so that we will be able to send requests via both ActiveMq and SQS so that we have a rollback path in case things don't work as expected.

4, 5, 6 -  Try and run the acceptance tests on the `tdl-client-java` project

7. I have a diagram but it is over simplified:
 https://github.com/julianghionoiu/tdl-client-spec

**Comment by neomatrix369** [comment]
Looking at the diagram https://github.com/julianghionoiu/tdl-client-spec isn't it a bit dated, certain things in that eco-system have changed? Hasn't the Web UI controls server interface changed?

When we run the test mentioned points 2 and 4,5,6 which component acts as the server process?

**Comment by julianghionoiu** [comment]
The diagram is out of date, but the queue interaction stays the same.
The Web UI has been replaced with a REST interface.

**Comment by neomatrix369** [comment]
Results of experimenting with current setup:
- acceptance tests on tdl-client-java work against the broker and wiremock setup provided (additional scripts now invoke them by default)
- elasticmq server (tdl-local-sqs) also works fine when queue-client is used to send a message to the queue, which means we can run the elasticmq server (tdl-local-sqs) instead of the broker (activemq) server and use the features of queue-client to send and receive messages to it

The last part with `running the elasticmq server (tdl-local-sqs) instead of the broker (activemq) server,  merging queue-client into tdl-client-java and running the acceptances` is pending implementing and testing. [See the changes](https://github.com/julianghionoiu/tdl-client-java/pull/7/files) to the start and stop scripts to take the first step in this direction.
